name: build-images
on: [pull_request]
jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GO111MODULE: on
      REPOSITORY: nfvpe/multi-networkpolicy
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build latest-amd64
        run: docker build -t ${REPOSITORY}:latest-amd64 .
